#!/bin/bash

apt install -y gsettings
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 15
gsettings set org.gnome.desktop.peripherals.keyboard delay 100

apt install -y xset
xset r rate 100 15

apt install -y imwheel
imwheel -b "4 5" > /dev/null 2>&1

curl -L -o chatgpt https://github.com/kardolus/chatgpt-cli/releases/latest/download/chatgpt-linux-amd64 && chmod +x chatgpt && sudo mv chatgpt /usr/local/bin/
echo -e "See https://platform.openai.com/account/api-keys for your API key.\nPlease enter your API key: "
read API_KEY 
cp $user_home/.bashrc $user_home/_.bashrc 	# Creates a backup of the bash config file
echo -e "export OPENAI_API_KEY=\"$API_KEY\"" >> $user_home/.bashrc
. $user_home/.bashrc
mkdir -p $user_home/.chatgpt-cli

# Installs and configures vim
apt install -y vim
cp $user_home/.vimrc $user_home/_.vimrc
cp -f ./.vimrc $user_home/.vimrc
