#!/bin/bash

user_home=$(eval echo ~$SUDO_USER)

# Installs gsettings and adjust settings for terminal repeat rate
apt install -y gnome-shell
dnf install -y gnome-shell

# Install xset and adjusts settings for GUI repeat rate
apt install -y xset
dnf install -y xset
xset r rate 100 15

# Installs and configures a fix for a mouse wheel bug in VMWare
apt install -y imwheel
dnf install -y imwheel
imwheel -b "4 5" > /dev/null 2>&1

apt install -y vim
dnf install -y vim

# Installs a CLI version of ChatGPT
curl -L -o chatgpt https://github.com/kardolus/chatgpt-cli/releases/latest/download/chatgpt-linux-amd64 && chmod +x chatgpt && sudo mv chatgpt /usr/local/bin/gpt

# Prompts user for OpenAI API Key
echo -e "\n\n\nSee  https://platform.openai.com/account/api-keys  for your API key.\nPlease enter your API key: "
read API_KEY 


# Finalizes some configurations
cp $user_home/.bashrc $user_home/_.bashrc 	# Creates a backup of the bash config file
echo -e "export OPENAI_API_KEY=\"$API_KEY\"" >> $user_home/.bashrc
echo -e "gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 15"
echo -e "gsettings set org.gnome.desktop.peripherals.keyboard delay 100"
mkdir -p $user_home/.chatgpt-cli
cp $user_home/.vimrc $user_home/_.vimrc
cp -f ./.vimrc $user_home/.vimrc

# Prompts to user to reset their bashrc
echo -e "\n\n\nRun \". ~/.bashrc\" to complete the configuration."
